ALTER TABLE food_items ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS quantity NUMERIC(10,2);
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS notes TEXT;
